version: '2'

services:
  nginx:
    build: ./nginx
    ports:
     - 8000:80
    volumes:
    - ../crm_schools_backend:/data/crm_schools/httpdocs
    depends_on:
    - mysql
    - php-fpm
  shell:
    build: ./shell
    container_name: shell
    volumes:
    - ../crm_schools_backend:/data/crm_schools/httpdocs
    - ../crm_schools_frontend:/data/crm_schools/httpdocs_angular
    depends_on:
    - mysql
    - redis
    - php-fpm
    - angular
  php-fpm:
    build: ./php-fpm
    volumes:
    - ../crm_schools_backend:/data/crm_schools/httpdocs
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
     - PMA_ARBITRARY=1
    ports:
     - 8080:80
    volumes:
     - /sessions
    external_links:
        - mysql
    depends_on:
    - mysql
  redis:
    image: 'redis:alpine'
    ports:
     - 6379:6379
  angular:
   build: ./angular
   ports:
    - 4200:4200
   volumes:
    - ../crm_schools_frontend:/data/crm_schools/httpdocs_angular
   depends_on:
   - nginx
  mysql:
    image: 'percona:5.6'
    volumes:
     - ./mysqldata:/var/lib/mysql
     - ./percona/my.cnf:/etc/my.cnf
    environment:
      MYSQL_DATABASE: 'crm_schools'
      MYSQL_ROOT_PASSWORD: 'admin'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'false'
    ports:
      - 3307:3306
  artisan:
    build: ./artisan
    volumes:
    - ../crm_schools_backend:/data/crm_schools/httpdocs
    depends_on:
     - mysql


